import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { Switch } from "@/components/ui/switch";
import {
  Activity,
  AlertTriangle,
  Bell,
  Bot,
  ChevronRight,
  Clock,
  DollarSign,
  FileText,
  GitBranch,
  MoreHorizontal,
  Pause,
  Play,
  Shield,
  TrendingUp,
  X,
  Zap,
} from "lucide-react";
import { motion } from "motion/react";
import { useState } from "react";
import type { MarketData } from "../engine/ChatEngine";

const WORKFLOWS = [
  {
    id: 1,
    name: "NVDA Confidence Monitor",
    status: "Running",
    lastRun: "7 min ago",
    quota: 12,
    consent: true,
  },
  {
    id: 2,
    name: "Portfolio Auto-Simulate",
    status: "Paused",
    lastRun: "2 hrs ago",
    quota: 40,
    consent: true,
  },
  {
    id: 3,
    name: "Daily Brief Generator",
    status: "Running",
    lastRun: "Sent 8:00 AM",
    quota: 5,
    consent: true,
  },
];

const CONSENTS = [
  {
    id: 1,
    name: "Portfolio Holdings",
    usedBy: "NVDA Monitor",
    expiry: "Jan 2025",
    active: true,
  },
  {
    id: 2,
    name: "Market Confidence Scores",
    usedBy: "Auto-Simulate",
    expiry: "Dec 2024",
    active: true,
  },
  {
    id: 3,
    name: "Alert Preferences",
    usedBy: "Daily Brief",
    expiry: "Permanent",
    active: true,
  },
];

const AUDIT_LOG = [
  {
    id: 1,
    action: "Workflow triggered",
    detail: "NVDA Monitor fired at $179.40",
    time: "2 min ago",
    type: "workflow",
  },
  {
    id: 2,
    action: "Price alert sent",
    detail: "TSLA crossed $245 threshold",
    time: "18 min ago",
    type: "alert",
  },
  {
    id: 3,
    action: "Consent renewed",
    detail: "Portfolio Holdings — extended 30d",
    time: "1 hr ago",
    type: "consent",
  },
  {
    id: 4,
    action: "Daily brief delivered",
    detail: "Market summary sent via Daily Brief",
    time: "8 hrs ago",
    type: "workflow",
  },
  {
    id: 5,
    action: "Flow earnings credited",
    detail: "₹45 added from market data share",
    time: "1 day ago",
    type: "earn",
  },
];

const QUICK_ACTIONS = [
  { label: "Daily Brief", icon: FileText, desc: "Get today's market summary" },
  { label: "Monitor Stock", icon: Activity, desc: "Set up price alert" },
  { label: "Auto-Simulate", icon: Zap, desc: "Run portfolio simulation" },
  { label: "Build Workflow", icon: Play, desc: "Create automation" },
];

const AI_INSIGHTS = [
  {
    icon: TrendingUp,
    color: "text-green-400",
    bg: "bg-green-400/10 border-green-400/20",
    title: "NVDA Bullish Signal",
    desc: "Showing strong momentum driven by AI chip demand. AI Score: 8.7/10.",
  },
  {
    icon: AlertTriangle,
    color: "text-yellow-400",
    bg: "bg-yellow-400/10 border-yellow-400/20",
    title: "BTC Volume Spike",
    desc: "Unusual volume detected. Potential breakout within 4-6 hours.",
  },
  {
    icon: Shield,
    color: "text-red-400",
    bg: "bg-red-400/10 border-red-400/20",
    title: "Portfolio Risk: Medium-High",
    desc: "65% AI stock concentration. Consider diversifying into Finance or Energy.",
  },
  {
    icon: Zap,
    color: "text-primary",
    bg: "bg-primary/10 border-primary/20",
    title: "New Strategy Available",
    desc: '"Crypto Swing Strategy" generated by Kai AI — +8.7% last month.',
  },
];

const ASSET_NAMES: Record<string, string> = {
  NVDA: "NVIDIA",
  MSFT: "Microsoft",
  AAPL: "Apple",
  TSLA: "Tesla",
  AMZN: "Amazon",
  GOOGL: "Google",
  META: "Meta",
  AMD: "AMD",
  NFLX: "Netflix",
  JPM: "JPMorgan",
  BTC: "Bitcoin",
  ETH: "Ethereum",
};

const ASSET_INSIGHTS: Record<string, string> = {
  NVDA: "Strong bullish momentum with high AI confidence",
  MSFT: "Steady cloud growth, defensive AI play",
  AAPL: "Consumer strength; premium valuation holds",
  TSLA: "High volatility — swing opportunity detected",
  AMZN: "AWS acceleration driving upside",
  GOOGL: "Ad recovery + Gemini AI tailwinds",
  META: "Reels monetization exceeding estimates",
  AMD: "Data center GPU demand surging",
  NFLX: "Ad-tier growth beating expectations",
  JPM: "Rate environment favorable; strong buybacks",
  BTC: "Institutional inflow accelerating",
  ETH: "ETF approval momentum building",
};

interface NotificationItem {
  id: number;
  text: string;
  type: "signal" | "strategy" | "alert";
  time: string;
}

const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 1,
    text: "NVDA Momentum Analyzer generated a BUY signal",
    type: "signal",
    time: "2 min ago",
  },
  {
    id: 2,
    text: "AI Growth Strategy up +2.1% today",
    type: "strategy",
    time: "15 min ago",
  },
  {
    id: 3,
    text: "TSLA price alert triggered at $248",
    type: "alert",
    time: "31 min ago",
  },
];

const NOTIFICATION_DOT: Record<string, string> = {
  signal: "bg-primary",
  strategy: "bg-green-400",
  alert: "bg-yellow-400",
};

interface Props {
  markets: MarketData[];
  onOpenChat: (msg?: string) => void;
  onSwitchToFlows?: () => void;
  onSwitchToTrade?: (symbol: string) => void;
}

export function Dashboard({
  markets,
  onOpenChat,
  onSwitchToFlows,
  onSwitchToTrade,
}: Props) {
  const [consents, setConsents] = useState(CONSENTS.map((c) => c.active));
  const [monetizationEnabled, setMonetizationEnabled] = useState(true);
  const [autoMode, setAutoMode] = useState(false);
  const [notifications, setNotifications] = useState<NotificationItem[]>(
    INITIAL_NOTIFICATIONS,
  );

  const totalValue = "₹4,12,560";
  const activeFlows = 3;
  const monthlyEarnings = "₹312";
  const riskLevel = "Medium-High";

  // Proactive alert from market data
  const highVolatility = markets.filter((m) => m.volatility === "High");
  const topPerformer = markets.length
    ? markets.reduce((a, b) => (a.change > b.change ? a : b))
    : null;

  // Top 3 opportunities by AI score
  const topOpps = [...markets]
    .sort((a, b) => b.aiScore - a.aiScore)
    .slice(0, 3);

  const dismissNotification = (id: number) => {
    setNotifications((prev) => prev.filter((n) => n.id !== id));
  };

  return (
    <div className="space-y-6">
      {/* Auto Mode Banner */}
      <motion.div
        initial={{ opacity: 0, y: -8 }}
        animate={{ opacity: 1, y: 0 }}
        className="flex items-center justify-between rounded-xl border border-border bg-card px-5 py-4"
        data-ocid="dashboard.panel"
      >
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-primary/15 border border-primary/30 flex items-center justify-center">
            <Bot className="h-5 w-5 text-primary" />
          </div>
          <div>
            <div className="font-display font-semibold text-foreground flex items-center gap-2">
              Kai Agent
              {autoMode && (
                <Badge className="bg-green-500/20 text-green-400 border-green-500/30 text-[10px] animate-pulse">
                  ● AUTO MODE ACTIVE
                </Badge>
              )}
            </div>
            <div className="text-xs text-muted-foreground">
              Autonomous AI financial operating system
            </div>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <span className="text-xs text-muted-foreground hidden sm:block">
            Auto Mode
          </span>
          <Switch
            checked={autoMode}
            onCheckedChange={setAutoMode}
            data-ocid="dashboard.switch"
          />
        </div>
      </motion.div>

      {/* Quick Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
        {[
          {
            label: "Portfolio Value",
            value: totalValue,
            sub: "+4.6% today",
            color: "text-green-400",
          },
          {
            label: "Active Flows",
            value: activeFlows.toString(),
            sub: "2 running · 1 paused",
            color: "text-primary",
          },
          {
            label: "Monthly Earnings",
            value: monthlyEarnings,
            sub: "Flow monetization",
            color: "text-yellow-400",
          },
          {
            label: "Risk Level",
            value: riskLevel,
            sub: "AI-assessed",
            color: "text-orange-400",
          },
        ].map((stat, i) => (
          <motion.div
            key={stat.label}
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.06 }}
            className="bg-card border border-border rounded-xl p-4"
            data-ocid={`dashboard.card.${i + 1}`}
          >
            <div className="text-[10px] text-muted-foreground uppercase tracking-wider mb-1">
              {stat.label}
            </div>
            <div className={`font-display text-xl font-bold ${stat.color}`}>
              {stat.value}
            </div>
            <div className="text-[10px] text-muted-foreground mt-0.5">
              {stat.sub}
            </div>
          </motion.div>
        ))}
      </div>

      {/* Top Opportunities Today */}
      <motion.section
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.08 }}
        className="bg-card border border-border rounded-xl p-5"
        data-ocid="opportunities.panel"
      >
        <div className="flex items-center gap-2 mb-4">
          <Zap className="h-4 w-4 text-yellow-400" />
          <h2 className="font-display font-semibold text-foreground">
            Top Opportunities Today
          </h2>
          <Badge className="ml-1 bg-green-500/20 text-green-400 border-green-500/30 text-[10px] animate-pulse">
            ● Live
          </Badge>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
          {topOpps.map((asset, i) => (
            <div
              key={asset.symbol}
              className="p-4 rounded-xl border border-border bg-secondary/30 flex flex-col gap-2"
              data-ocid={`opportunities.item.${i + 1}`}
            >
              <div className="flex items-center justify-between">
                <div>
                  <span className="font-display font-bold text-foreground text-base">
                    {asset.symbol}
                  </span>
                  <p className="text-[10px] text-muted-foreground">
                    {ASSET_NAMES[asset.symbol] ?? asset.symbol}
                  </p>
                </div>
                <Badge
                  variant="outline"
                  className="text-[10px] border-primary/40 text-primary"
                >
                  {asset.confidence}% confidence
                </Badge>
              </div>
              <p className="text-[11px] text-muted-foreground leading-relaxed">
                {ASSET_INSIGHTS[asset.symbol] ??
                  "Strong signal detected by Kai AI."}
              </p>
              <Button
                size="sm"
                className="h-7 text-xs bg-primary/15 hover:bg-primary/25 text-primary border border-primary/30 rounded-lg mt-1"
                variant="ghost"
                onClick={() => onSwitchToTrade?.(asset.symbol)}
                data-ocid={`opportunities.button.${i + 1}`}
              >
                Trade → {asset.symbol}
              </Button>
            </div>
          ))}
        </div>
      </motion.section>

      {/* AI Overview Panel */}
      <motion.section
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
        className="bg-card border border-border rounded-xl p-5"
        data-ocid="aiinsights.panel"
      >
        <div className="flex items-center gap-2 mb-4">
          <Zap className="h-4 w-4 text-primary" />
          <h2 className="font-display font-semibold text-foreground">
            Kai AI Insights
          </h2>
          <Badge
            variant="outline"
            className="ml-auto text-[10px] border-primary/40 text-primary"
          >
            {AI_INSIGHTS.length} active
          </Badge>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
          {AI_INSIGHTS.map((insight, i) => (
            <button
              type="button"
              key={insight.title}
              onClick={() => onOpenChat(insight.title)}
              className={`text-left p-3 rounded-xl border ${insight.bg} hover:brightness-110 transition-all`}
              data-ocid={`aiinsights.item.${i + 1}`}
            >
              <insight.icon className={`h-4 w-4 ${insight.color} mb-2`} />
              <div className="text-xs font-semibold text-foreground mb-1">
                {insight.title}
              </div>
              <div className="text-[10px] text-muted-foreground leading-relaxed">
                {insight.desc}
              </div>
            </button>
          ))}
        </div>

        {/* Market-driven alert */}
        {highVolatility.length > 0 && (
          <div className="mt-3 flex items-center gap-2 text-xs text-yellow-400 bg-yellow-400/8 border border-yellow-400/20 rounded-lg px-3 py-2">
            <AlertTriangle className="h-3.5 w-3.5 shrink-0" />
            <span>
              <strong>Live Alert:</strong>{" "}
              {highVolatility.map((m) => m.symbol).join(", ")} showing high
              volatility —
              {topPerformer &&
                ` ${topPerformer.symbol} leading at +${Math.max(0, topPerformer.change).toFixed(2)}%`}
            </span>
            <Button
              size="sm"
              variant="ghost"
              className="ml-auto h-6 text-[10px] text-yellow-400 hover:text-yellow-300 shrink-0"
              onClick={() => onOpenChat("market alerts")}
              data-ocid="aiinsights.button"
            >
              View <ChevronRight className="h-3 w-3 ml-0.5" />
            </Button>
          </div>
        )}
      </motion.section>

      {/* Smart Notifications */}
      {notifications.length > 0 && (
        <motion.section
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.15 }}
          className="bg-card border border-border rounded-xl p-5"
          data-ocid="notifications.panel"
        >
          <div className="flex items-center gap-2 mb-3">
            <Bell className="h-4 w-4 text-primary" />
            <h2 className="font-display font-semibold text-foreground">
              Notifications
            </h2>
            <Badge className="ml-1 bg-primary/20 text-primary border-primary/30 text-[10px]">
              {notifications.length}
            </Badge>
          </div>
          <div className="space-y-2">
            {notifications.map((n, i) => (
              <div
                key={n.id}
                className="flex items-center gap-3 p-3 rounded-lg bg-secondary/40 border border-border"
                data-ocid={`notifications.item.${i + 1}`}
              >
                <span
                  className={`h-2 w-2 rounded-full shrink-0 ${NOTIFICATION_DOT[n.type]}`}
                />
                <span className="flex-1 text-xs text-foreground">{n.text}</span>
                <span className="text-[10px] text-muted-foreground shrink-0">
                  {n.time}
                </span>
                <button
                  type="button"
                  onClick={() => dismissNotification(n.id)}
                  className="text-muted-foreground hover:text-foreground transition-colors shrink-0"
                  data-ocid={`notifications.close_button.${i + 1}`}
                >
                  <X className="h-3.5 w-3.5" />
                </button>
              </div>
            ))}
          </div>
        </motion.section>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Active Workflows */}
        <motion.section
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.15 }}
          className="lg:col-span-2 bg-card border border-border rounded-xl p-5"
        >
          <div className="flex items-center justify-between mb-4">
            <h2 className="font-display font-semibold text-foreground">
              Active Workflows
            </h2>
            <Button
              variant="ghost"
              size="sm"
              className="text-primary text-xs h-7"
              onClick={onSwitchToFlows}
              data-ocid="workflow.button"
            >
              <GitBranch className="h-3 w-3 mr-1" /> Manage Flows
            </Button>
          </div>
          <div className="space-y-3">
            {WORKFLOWS.map((wf, i) => (
              <div
                key={wf.id}
                className="flex items-center gap-4 p-3 rounded-lg bg-secondary/40 border border-border"
                data-ocid={`workflow.item.${i + 1}`}
              >
                <div
                  className={`w-2 h-2 rounded-full shrink-0 ${wf.status === "Running" ? "bg-green-400 animate-pulse" : "bg-yellow-400"}`}
                />
                <div className="flex-1 min-w-0">
                  <div className="text-sm font-medium text-foreground truncate">
                    {wf.name}
                  </div>
                  <div className="text-xs text-muted-foreground">
                    {wf.lastRun} · Consent {wf.consent ? "Valid" : "Expired"}
                  </div>
                </div>
                <Badge
                  variant="outline"
                  className={`text-[10px] shrink-0 ${wf.status === "Running" ? "border-green-500/40 text-green-400" : "border-yellow-500/40 text-yellow-400"}`}
                >
                  {wf.status === "Running" ? (
                    <>
                      <Play className="h-2.5 w-2.5 mr-1" />
                      Running
                    </>
                  ) : (
                    <>
                      <Pause className="h-2.5 w-2.5 mr-1" />
                      Paused
                    </>
                  )}
                </Badge>
                <div className="text-[10px] text-muted-foreground shrink-0">
                  {wf.quota}% quota
                </div>
                <Button
                  variant="ghost"
                  size="icon"
                  className="h-6 w-6 text-muted-foreground shrink-0"
                >
                  <MoreHorizontal className="h-3.5 w-3.5" />
                </Button>
              </div>
            ))}
          </div>
        </motion.section>

        {/* Flow Monetization */}
        <motion.section
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="bg-card border border-border rounded-xl p-5"
        >
          <div className="flex items-center gap-2 mb-4">
            <DollarSign className="h-4 w-4 text-primary" />
            <h2 className="font-display font-semibold text-foreground">
              Flow Earnings
            </h2>
          </div>
          <div className="text-3xl font-display font-bold text-foreground mb-1">
            ₹312
          </div>
          <div className="text-xs text-muted-foreground mb-5">
            This month · 3 active flows
          </div>
          <div className="space-y-3 mb-5">
            {[
              {
                label: "You (40%)",
                value: 40,
                amount: "₹124.80",
                color: "bg-green-500",
              },
              {
                label: "Kai AI (30%)",
                value: 30,
                amount: "₹93.60",
                color: "bg-primary",
              },
              {
                label: "Brands (30%)",
                value: 30,
                amount: "₹93.60",
                color: "bg-purple-500",
              },
            ].map((r) => (
              <div key={r.label}>
                <div className="flex justify-between text-xs mb-1">
                  <span className="text-muted-foreground">{r.label}</span>
                  <span className="text-foreground font-medium">
                    {r.amount}
                  </span>
                </div>
                <Progress value={r.value} className="h-1.5" />
              </div>
            ))}
          </div>
          <div className="flex items-center justify-between">
            <span className="text-xs text-muted-foreground">New workflows</span>
            <Switch
              checked={monetizationEnabled}
              onCheckedChange={setMonetizationEnabled}
              data-ocid="monetization.switch"
            />
          </div>
        </motion.section>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Consent Panel */}
        <motion.section
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.25 }}
          className="lg:col-span-2 bg-card border border-border rounded-xl p-5"
        >
          <div className="flex items-center gap-2 mb-4">
            <Shield className="h-4 w-4 text-primary" />
            <h2 className="font-display font-semibold text-foreground">
              Consent & Trust Panel
            </h2>
            <Badge
              variant="outline"
              className="ml-auto text-[10px] border-green-500/40 text-green-400"
            >
              3/3 Active
            </Badge>
          </div>
          <div className="space-y-3">
            {CONSENTS.map((c, i) => (
              <div
                key={c.id}
                className="flex items-center justify-between p-3 rounded-lg bg-secondary/40 border border-border"
                data-ocid={`consent.item.${i + 1}`}
              >
                <div>
                  <div className="text-sm font-medium text-foreground">
                    {c.name}
                  </div>
                  <div className="text-xs text-muted-foreground">
                    Used by: {c.usedBy} · Expires {c.expiry}
                  </div>
                </div>
                <Switch
                  checked={consents[i]}
                  onCheckedChange={(v) =>
                    setConsents((prev) => prev.map((p, j) => (j === i ? v : p)))
                  }
                  data-ocid={`consent.switch.${i + 1}`}
                />
              </div>
            ))}
          </div>
        </motion.section>

        {/* Audit Log */}
        <motion.section
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
          className="bg-card border border-border rounded-xl p-5"
        >
          <div className="flex items-center gap-2 mb-4">
            <Clock className="h-4 w-4 text-primary" />
            <h2 className="font-display font-semibold text-foreground">
              Audit Log
            </h2>
          </div>
          <div className="space-y-3">
            {AUDIT_LOG.map((log, i) => (
              <div
                key={log.id}
                className="flex gap-3"
                data-ocid={`audit.item.${i + 1}`}
              >
                <div className="w-1.5 h-1.5 rounded-full bg-primary mt-2 shrink-0" />
                <div>
                  <div className="text-xs font-medium text-foreground">
                    {log.action}
                  </div>
                  <div className="text-[10px] text-muted-foreground">
                    {log.detail}
                  </div>
                  <div className="text-[10px] text-muted-foreground opacity-60">
                    {log.time}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </motion.section>
      </div>

      {/* Quick Actions */}
      <motion.section
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.35 }}
        className="bg-card border border-border rounded-xl p-5"
      >
        <h2 className="font-display font-semibold text-foreground mb-4">
          Quick Actions
        </h2>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
          {QUICK_ACTIONS.map((qa, i) => (
            <button
              type="button"
              key={qa.label}
              onClick={() => onOpenChat(qa.label.toLowerCase())}
              className="p-4 rounded-xl border border-border bg-secondary/30 hover:border-primary/40 hover:bg-primary/5 transition-all group text-left"
              data-ocid={`quickaction.button.${i + 1}`}
            >
              <qa.icon className="h-5 w-5 text-primary mb-2 group-hover:scale-110 transition-transform" />
              <div className="text-sm font-medium text-foreground">
                {qa.label}
              </div>
              <div className="text-[10px] text-muted-foreground mt-0.5">
                {qa.desc}
              </div>
            </button>
          ))}
        </div>
      </motion.section>
    </div>
  );
}
