/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SessionId = IDL.Text;
export const Time = IDL.Int;
export const Message = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addMessage' : IDL.Func([SessionId, Message], [], []),
  'createSession' : IDL.Func([SessionId], [], []),
  'getAllSessions' : IDL.Func([], [IDL.Vec(SessionId)], ['query']),
  'getMessages' : IDL.Func([SessionId], [IDL.Vec(Message)], ['query']),
  'is2FAEnabled' : IDL.Func([], [IDL.Bool], ['query']),
  'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'register' : IDL.Func([], [], []),
  'set2FAEnabled' : IDL.Func([IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SessionId = IDL.Text;
  const Time = IDL.Int;
  const Message = IDL.Record({
    'content' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'addMessage' : IDL.Func([SessionId, Message], [], []),
    'createSession' : IDL.Func([SessionId], [], []),
    'getAllSessions' : IDL.Func([], [IDL.Vec(SessionId)], ['query']),
    'getMessages' : IDL.Func([SessionId], [IDL.Vec(Message)], ['query']),
    'is2FAEnabled' : IDL.Func([], [IDL.Bool], ['query']),
    'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'register' : IDL.Func([], [], []),
    'set2FAEnabled' : IDL.Func([IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };